.TH "src/main/java/frc/robot/autonomous/actions Directory Reference" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/java/frc/robot/autonomous/actions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCrawl\&.java\fP"
.br
.ti -1c
.RI "file \fBCrawlAndHoldBot\&.java\fP"
.br
.ti -1c
.RI "file \fBDriveAndRetractArms\&.java\fP"
.br
.ti -1c
.RI "file \fBFollowPath\&.java\fP"
.br
.ti -1c
.RI "file \fBHoldArmsUntilLock\&.java\fP"
.br
.ti -1c
.RI "file \fBMoveArms\&.java\fP"
.br
.ti -1c
.RI "file \fBMoveArmsWithGradualForce\&.java\fP"
.br
.ti -1c
.RI "file \fBMoveLegs\&.java\fP"
.br
.ti -1c
.RI "file \fBRaiseBotToSetpoint\&.java\fP"
.br
.ti -1c
.RI "file \fBSetBrakes\&.java\fP"
.br
.ti -1c
.RI "file \fBSetClimberLock\&.java\fP"
.br
.ti -1c
.RI "file \fBSetFinger\&.java\fP"
.br
.ti -1c
.RI "file \fBSetLedring\&.java\fP"
.br
.ti -1c
.RI "file \fBSetPiston\&.java\fP"
.br
.ti -1c
.RI "file \fBSetPitchSetpoint\&.java\fP"
.br
.in -1c
