.TH "frc.lib5k.loops.loopers" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.lib5k.loops.loopers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLooper\fP"
.br
.RI "An abstract for anything that can be looped\&. "
.ti -1c
.RI "class \fBSubsystemLooper\fP"
.br
.RI "A looper for LoopableSubsystems\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
