.TH "frc.lib5k.utils.RobotLogger.Level" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.lib5k.utils.RobotLogger.Level \- Log level\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBkRobot\fP"
.br
.ti -1c
.RI "\fBkInfo\fP"
.br
.ti -1c
.RI "\fBkWarning\fP"
.br
.ti -1c
.RI "\fBkLibrary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Log level\&. 

The kRobot level will immeadiatly push to the console, everything else is queued until the next notifier cycle 
.PP
Definition at line 19 of file RobotLogger\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "frc\&.lib5k\&.utils\&.RobotLogger\&.Level\&.kInfo"

.PP
Definition at line 20 of file RobotLogger\&.java\&.
.SS "frc\&.lib5k\&.utils\&.RobotLogger\&.Level\&.kLibrary"

.PP
Definition at line 20 of file RobotLogger\&.java\&.
.SS "frc\&.lib5k\&.utils\&.RobotLogger\&.Level\&.kRobot"

.PP
Definition at line 20 of file RobotLogger\&.java\&.
.SS "frc\&.lib5k\&.utils\&.RobotLogger\&.Level\&.kWarning"

.PP
Definition at line 20 of file RobotLogger\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
