.TH "frc.robot.subsystems.Gyroscope" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.subsystems.Gyroscope
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGyroscope\fP ()"
.br
.ti -1c
.RI "AHRS \fBgetGyro\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGyroscope\fP \fBgetInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file Gyroscope\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.subsystems\&.Gyroscope\&.Gyroscope ()"

.PP
Definition at line 16 of file Gyroscope\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "AHRS frc\&.robot\&.subsystems\&.Gyroscope\&.getGyro ()"

.PP
Definition at line 32 of file Gyroscope\&.java\&.
.SS "static \fBGyroscope\fP frc\&.robot\&.subsystems\&.Gyroscope\&.getInstance ()\fC [static]\fP"

.PP
Definition at line 24 of file Gyroscope\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
