.TH "frc.robot.subsystems" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.subsystems
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCargoFlap\fP"
.br
.ti -1c
.RI "class \fBClimber\fP"
.br
.RI "Subsystem in charge of climb\&. "
.ti -1c
.RI "class \fBDriveTrain\fP"
.br
.RI "\fBDriveTrain\fP is the only class to not buffer it's outputs\&. "
.ti -1c
.RI "class \fBGyroscope\fP"
.br
.ti -1c
.RI "class \fBIntake\fP"
.br
.RI "The intake includes the slider, piston, finger, and all related sensors\&. "
.ti -1c
.RI "class \fBLEDring\fP"
.br
.ti -1c
.RI "class \fBPneumatics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
