.TH "frc.lib5k.components" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.lib5k.components
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAutoCamera\fP"
.br
.RI "Automatic camera streaming\&. "
.ti -1c
.RI "class \fBGearBox\fP"
.br
.RI "A \fBGearBox\fP is a wrapper for any pair of WPI_TalonSRX motor controllers where the first controller has an encoder attached\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
