.TH "frc.robot.autonomous.actions.SetPiston" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.actions.SetPiston
.SH SYNOPSIS
.br
.PP
.PP
Inherits TimedCommand\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetPiston\fP (boolean extended, double timeout)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "void \fBexecute\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file SetPiston\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.autonomous\&.actions\&.SetPiston\&.SetPiston (boolean extended, double timeout)"

.PP
Definition at line 12 of file SetPiston\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.autonomous\&.actions\&.SetPiston\&.execute ()\fC [protected]\fP"

.PP
Definition at line 27 of file SetPiston\&.java\&.
.SS "void frc\&.robot\&.autonomous\&.actions\&.SetPiston\&.initialize ()\fC [protected]\fP"

.PP
Definition at line 21 of file SetPiston\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
