.TH "frc.robot.autonomous.actions.MoveArmsWithGradualForce" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.actions.MoveArmsWithGradualForce
.SH SYNOPSIS
.br
.PP
.PP
Inherits Command\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveArmsWithGradualForce\fP (double starting_speed, double ending_speed, double cap_time_secs)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "void \fBexecute\fP ()"
.br
.ti -1c
.RI "void \fBend\fP ()"
.br
.ti -1c
.RI "boolean \fBisFinished\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file MoveArmsWithGradualForce\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.autonomous\&.actions\&.MoveArmsWithGradualForce\&.MoveArmsWithGradualForce (double starting_speed, double ending_speed, double cap_time_secs)"

.PP
Definition at line 19 of file MoveArmsWithGradualForce\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.autonomous\&.actions\&.MoveArmsWithGradualForce\&.end ()\fC [protected]\fP"

.PP
Definition at line 47 of file MoveArmsWithGradualForce\&.java\&.
.SS "void frc\&.robot\&.autonomous\&.actions\&.MoveArmsWithGradualForce\&.execute ()\fC [protected]\fP"

.PP
Definition at line 37 of file MoveArmsWithGradualForce\&.java\&.
.SS "void frc\&.robot\&.autonomous\&.actions\&.MoveArmsWithGradualForce\&.initialize ()\fC [protected]\fP"

.PP
Definition at line 30 of file MoveArmsWithGradualForce\&.java\&.
.SS "boolean frc\&.robot\&.autonomous\&.actions\&.MoveArmsWithGradualForce\&.isFinished ()\fC [protected]\fP"

.PP
Definition at line 52 of file MoveArmsWithGradualForce\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
