.TH "frc.robot.autonomous.actions.RaiseBotToSetpoint" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.actions.RaiseBotToSetpoint
.SH SYNOPSIS
.br
.PP
.PP
Inherits Command\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRaiseBotToSetpoint\fP (double leg_speed, double arm_speed, double pitch_threshold)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBexecute\fP ()"
.br
.ti -1c
.RI "boolean \fBisFinished\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file RaiseBotToSetpoint\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.autonomous\&.actions\&.RaiseBotToSetpoint\&.RaiseBotToSetpoint (double leg_speed, double arm_speed, double pitch_threshold)"

.PP
Definition at line 14 of file RaiseBotToSetpoint\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.autonomous\&.actions\&.RaiseBotToSetpoint\&.execute ()\fC [protected]\fP"

.PP
Definition at line 21 of file RaiseBotToSetpoint\&.java\&.
.SS "boolean frc\&.robot\&.autonomous\&.actions\&.RaiseBotToSetpoint\&.isFinished ()\fC [protected]\fP"

.PP
Definition at line 30 of file RaiseBotToSetpoint\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
