.TH "frc.robot.Constants.PCM" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.Constants.PCM
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBcan_id\fP = 11"
.br
.ti -1c
.RI "static final int \fBledring\fP = 0"
.br
.ti -1c
.RI "static final int \fBfinger_reverse\fP = 2"
.br
.ti -1c
.RI "static final int \fBfinger_forward\fP = 1"
.br
.ti -1c
.RI "static final int \fBpiston\fP = 7"
.br
.ti -1c
.RI "static final int \fBflap_forward\fP = 5"
.br
.ti -1c
.RI "static final int \fBflap_reverse\fP = 6"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file Constants\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final int frc\&.robot\&.Constants\&.PCM\&.can_id = 11\fC [static]\fP"

.PP
Definition at line 82 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.PCM\&.finger_forward = 1\fC [static]\fP"

.PP
Definition at line 85 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.PCM\&.finger_reverse = 2\fC [static]\fP"

.PP
Definition at line 84 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.PCM\&.flap_forward = 5\fC [static]\fP"

.PP
Definition at line 87 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.PCM\&.flap_reverse = 6\fC [static]\fP"

.PP
Definition at line 88 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.PCM\&.ledring = 0\fC [static]\fP"

.PP
Definition at line 83 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.PCM\&.piston = 7\fC [static]\fP"

.PP
Definition at line 86 of file Constants\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
