.TH "frc.robot.commands.IntakeControl" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.commands.IntakeControl \- Command for controlling intake commands from drivers\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Command\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntakeControl\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "void \fBexecute\fP ()"
.br
.ti -1c
.RI "boolean \fBisFinished\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Command for controlling intake commands from drivers\&. 
.PP
Definition at line 12 of file IntakeControl\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.commands\&.IntakeControl\&.IntakeControl ()"

.PP
Definition at line 29 of file IntakeControl\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.commands\&.IntakeControl\&.execute ()\fC [protected]\fP"

.PP
Definition at line 47 of file IntakeControl\&.java\&.
.SS "void frc\&.robot\&.commands\&.IntakeControl\&.initialize ()\fC [protected]\fP"

.PP
Definition at line 36 of file IntakeControl\&.java\&.
.SS "boolean frc\&.robot\&.commands\&.IntakeControl\&.isFinished ()\fC [protected]\fP"

.PP
Definition at line 104 of file IntakeControl\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
