.TH "frc.robot.autonomous.actions.SetClimberLock" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.actions.SetClimberLock
.SH SYNOPSIS
.br
.PP
.PP
Inherits Command\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetClimberLock\fP (boolean is_locked)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "boolean \fBisFinished\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file SetClimberLock\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.autonomous\&.actions\&.SetClimberLock\&.SetClimberLock (boolean is_locked)"

.PP
Definition at line 10 of file SetClimberLock\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.autonomous\&.actions\&.SetClimberLock\&.initialize ()\fC [protected]\fP"

.PP
Definition at line 16 of file SetClimberLock\&.java\&.
.SS "boolean frc\&.robot\&.autonomous\&.actions\&.SetClimberLock\&.isFinished ()\fC [protected]\fP"

.PP
Definition at line 27 of file SetClimberLock\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
