.TH "frc.robot.autonomous.commandgroups.Outtake" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.commandgroups.Outtake \- Handles everything required to shoot a hatch and drop a cargo\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits CommandGroup\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOuttake\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles everything required to shoot a hatch and drop a cargo\&. 
.PP
Definition at line 11 of file Outtake\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.autonomous\&.commandgroups\&.Outtake\&.Outtake ()"

.PP
Definition at line 13 of file Outtake\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
