.TH "frc.robot.subsystems.Pneumatics" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.subsystems.Pneumatics
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfrc\&.lib5k\&.loops\&.loopables\&.LoopableSubsystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPneumatics\fP ()"
.br
.ti -1c
.RI "void \fBperiodicOutput\fP ()"
.br
.ti -1c
.RI "void \fBsetPrimaryCompressorEnabled\fP (boolean on)"
.br
.ti -1c
.RI "void \fBoutputTelemetry\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPneumatics\fP \fBgetInstance\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file Pneumatics\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.subsystems\&.Pneumatics\&.Pneumatics ()"

.PP
Definition at line 21 of file Pneumatics\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBPneumatics\fP frc\&.robot\&.subsystems\&.Pneumatics\&.getInstance ()\fC [static]\fP"

.PP
Definition at line 29 of file Pneumatics\&.java\&.
.SS "void frc\&.robot\&.subsystems\&.Pneumatics\&.outputTelemetry ()"

.PP
Definition at line 69 of file Pneumatics\&.java\&.
.SS "void frc\&.robot\&.subsystems\&.Pneumatics\&.periodicOutput ()"

.PP
Definition at line 38 of file Pneumatics\&.java\&.
.SS "void frc\&.robot\&.subsystems\&.Pneumatics\&.reset ()"

.PP
Definition at line 80 of file Pneumatics\&.java\&.
.SS "void frc\&.robot\&.subsystems\&.Pneumatics\&.setPrimaryCompressorEnabled (boolean on)"

.PP
\fBParameters:\fP
.RS 4
\fIon\fP Should the primary compressor be enabled? 
.RE
.PP

.PP
Definition at line 56 of file Pneumatics\&.java\&.
.SS "void frc\&.robot\&.subsystems\&.Pneumatics\&.stop ()"

.PP
Definition at line 74 of file Pneumatics\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
