.TH "frc.robot.autonomous.Chooser" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.Chooser \- Reads inputs from smartdashboard to determine correct auto to run\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChooser\fP ()"
.br
.RI "Create a chooser and register with smartdashboard\&. "
.ti -1c
.RI "CommandGroup \fBgetAutonomousCommand\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reads inputs from smartdashboard to determine correct auto to run\&. 
.PP
Definition at line 15 of file Chooser\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.autonomous\&.Chooser\&.Chooser ()"

.PP
Create a chooser and register with smartdashboard\&. 
.PP
Definition at line 22 of file Chooser\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "CommandGroup frc\&.robot\&.autonomous\&.Chooser\&.getAutonomousCommand ()"

.PP
Definition at line 40 of file Chooser\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
