.TH "frc.lib5k.control.ToggleTest" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.lib5k.control.ToggleTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToggleTest\fP ()"
.br
.ti -1c
.RI "void \fBtestToggle\fP ()"
.br
.ti -1c
.RI "void \fBtestToggleReset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file ToggleTest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.lib5k\&.control\&.ToggleTest\&.ToggleTest ()"

.PP
Definition at line 11 of file ToggleTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.lib5k\&.control\&.ToggleTest\&.testToggle ()"

.PP
Definition at line 16 of file ToggleTest\&.java\&.
.SS "void frc\&.lib5k\&.control\&.ToggleTest\&.testToggleReset ()"

.PP
Definition at line 27 of file ToggleTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
