.TH "frc.lib5k.utils.Consts" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.lib5k.utils.Consts
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final double \fBkEpsilon\fP = 1E\-9"
.br
.ti -1c
.RI "static final double \fBPI\fP = 3\&.14159"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Consts\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final double frc\&.lib5k\&.utils\&.Consts\&.kEpsilon = 1E\-9\fC [static]\fP"

.PP
Definition at line 4 of file Consts\&.java\&.
.SS "final double frc\&.lib5k\&.utils\&.Consts\&.PI = 3\&.14159\fC [static]\fP"

.PP
Definition at line 5 of file Consts\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
