.TH "frc.robot.Locks" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.Locks
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLocks\fP \fBgetInstance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBLocks\fP \fBmInstance\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Locks\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBLocks\fP frc\&.robot\&.Locks\&.getInstance ()\fC [static]\fP"

.PP
Definition at line 6 of file Locks\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLocks\fP frc\&.robot\&.Locks\&.mInstance = null\fC [static]\fP"

.PP
Definition at line 4 of file Locks\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
