.TH "frc.robot.subsystems.CargoFlap" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.subsystems.CargoFlap
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfrc\&.lib5k\&.loops\&.loopables\&.LoopableSubsystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCargoFlap\fP ()"
.br
.ti -1c
.RI "void \fBperiodicOutput\fP ()"
.br
.ti -1c
.RI "void \fBsetFlapLowered\fP (boolean isFlapLowered)"
.br
.ti -1c
.RI "void \fBoutputTelemetry\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file CargoFlap\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.subsystems\&.CargoFlap\&.CargoFlap ()"

.PP
Definition at line 19 of file CargoFlap\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.subsystems\&.CargoFlap\&.outputTelemetry ()"

.PP
Definition at line 48 of file CargoFlap\&.java\&.
.SS "void frc\&.robot\&.subsystems\&.CargoFlap\&.periodicOutput ()"

.PP
Definition at line 29 of file CargoFlap\&.java\&.
.SS "void frc\&.robot\&.subsystems\&.CargoFlap\&.reset ()"

.PP
Definition at line 58 of file CargoFlap\&.java\&.
.SS "void frc\&.robot\&.subsystems\&.CargoFlap\&.setFlapLowered (boolean isFlapLowered)"

.PP
\fBParameters:\fP
.RS 4
\fIisFlapLowered\fP Should the flap be lowered 
.RE
.PP

.PP
Definition at line 42 of file CargoFlap\&.java\&.
.SS "void frc\&.robot\&.subsystems\&.CargoFlap\&.stop ()"

.PP
Definition at line 53 of file CargoFlap\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
