.TH "frc.lib5k.control.SlewLimiterTest" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.lib5k.control.SlewLimiterTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSlewLimiterTest\fP ()"
.br
.ti -1c
.RI "void \fBtestPositiveSlewRate\fP ()"
.br
.ti -1c
.RI "void \fBtestSlewReset\fP ()"
.br
.ti -1c
.RI "void \fBtestNegativeSlewRate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file SlewLimiterTest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.lib5k\&.control\&.SlewLimiterTest\&.SlewLimiterTest ()"

.PP
Definition at line 14 of file SlewLimiterTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.lib5k\&.control\&.SlewLimiterTest\&.testNegativeSlewRate ()"

.PP
Definition at line 38 of file SlewLimiterTest\&.java\&.
.SS "void frc\&.lib5k\&.control\&.SlewLimiterTest\&.testPositiveSlewRate ()"

.PP
Definition at line 20 of file SlewLimiterTest\&.java\&.
.SS "void frc\&.lib5k\&.control\&.SlewLimiterTest\&.testSlewReset ()"

.PP
Definition at line 31 of file SlewLimiterTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
