.TH "frc.robot.autonomous.actions.DriveAndRetractArms" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.actions.DriveAndRetractArms
.SH SYNOPSIS
.br
.PP
.PP
Inherits TimedCommand\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDriveAndRetractArms\fP (double drive_speed_start, double drive_speed_end, double arm_speed, double leg_speed, double timeout)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "void \fBexecute\fP ()"
.br
.ti -1c
.RI "void \fBend\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file DriveAndRetractArms\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.autonomous\&.actions\&.DriveAndRetractArms\&.DriveAndRetractArms (double drive_speed_start, double drive_speed_end, double arm_speed, double leg_speed, double timeout)"

.PP
Definition at line 19 of file DriveAndRetractArms\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.autonomous\&.actions\&.DriveAndRetractArms\&.end ()\fC [protected]\fP"

.PP
Definition at line 48 of file DriveAndRetractArms\&.java\&.
.SS "void frc\&.robot\&.autonomous\&.actions\&.DriveAndRetractArms\&.execute ()\fC [protected]\fP"

.PP
Definition at line 37 of file DriveAndRetractArms\&.java\&.
.SS "void frc\&.robot\&.autonomous\&.actions\&.DriveAndRetractArms\&.initialize ()\fC [protected]\fP"

.PP
Definition at line 31 of file DriveAndRetractArms\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
