.TH "frc.robot.autonomous.actions" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.actions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCrawl\fP"
.br
.ti -1c
.RI "class \fBCrawlAndHoldBot\fP"
.br
.ti -1c
.RI "class \fBDriveAndRetractArms\fP"
.br
.ti -1c
.RI "class \fBFollowPath\fP"
.br
.ti -1c
.RI "class \fBHoldArmsUntilLock\fP"
.br
.RI "Hold the arms at a speed until the climber is 'locked'\&. "
.ti -1c
.RI "class \fBMoveArms\fP"
.br
.ti -1c
.RI "class \fBMoveArmsWithGradualForce\fP"
.br
.ti -1c
.RI "class \fBMoveLegs\fP"
.br
.ti -1c
.RI "class \fBRaiseBotToSetpoint\fP"
.br
.ti -1c
.RI "class \fBSetBrakes\fP"
.br
.RI "Sets the DriveTrain's brakes in autonomous\&. "
.ti -1c
.RI "class \fBSetClimberLock\fP"
.br
.ti -1c
.RI "class \fBSetFinger\fP"
.br
.ti -1c
.RI "class \fBSetLedring\fP"
.br
.ti -1c
.RI "class \fBSetPiston\fP"
.br
.ti -1c
.RI "class \fBSetPitchSetpoint\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
