.TH "frc.lib5k.control" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.lib5k.control
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCubicDeadband\fP"
.br
.RI "This Scaling method was inspired by this blog post: "
.ti -1c
.RI "class \fBSlewLimiter\fP"
.br
.ti -1c
.RI "class \fBSlewLimiterTest\fP"
.br
.ti -1c
.RI "class \fBToggle\fP"
.br
.ti -1c
.RI "class \fBToggleTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
