.TH "frc.robot.autonomous" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBactions\fP"
.br
.ti -1c
.RI "package \fBcommandgroups\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChooser\fP"
.br
.RI "Reads inputs from smartdashboard to determine correct auto to run\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
