.TH "frc.lib5k.control.Toggle" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.lib5k.control.Toggle
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBfeed\fP (boolean input)"
.br
.ti -1c
.RI "boolean \fBget\fP ()"
.br
.RI "This is to be used in a situation were you are not looking to toggle the value, just read\&. "
.ti -1c
.RI "void \fBreset\fP ()"
.br
.RI "Reset the current output\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Toggle\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean frc\&.lib5k\&.control\&.Toggle\&.feed (boolean input)"

.PP
Definition at line 6 of file Toggle\&.java\&.
.SS "boolean frc\&.lib5k\&.control\&.Toggle\&.get ()"

.PP
This is to be used in a situation were you are not looking to toggle the value, just read\&. 
.PP
\fBReturns:\fP
.RS 4
Current output of the \fBToggle\fP 
.RE
.PP

.PP
Definition at line 22 of file Toggle\&.java\&.
.SS "void frc\&.lib5k\&.control\&.Toggle\&.reset ()"

.PP
Reset the current output\&. 
.PP
Definition at line 29 of file Toggle\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
