.TH "frc.robot.autonomous.commandgroups.Climb" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.commandgroups.Climb \- This should be used for going lvl 1 to 3, or 2 to 3\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits CommandGroup\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClimb\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinterrupted\fP ()"
.br
.ti -1c
.RI "void \fBend\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This should be used for going lvl 1 to 3, or 2 to 3\&. 

NOT 1 to 2\&. That should be done with manual control
.PP
For manual control, a button must be held, which unlocks the arms, and forces the crawl to move forward at 100% 
.PP
Definition at line 20 of file Climb\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.autonomous\&.commandgroups\&.Climb\&.Climb ()"

.PP
Definition at line 22 of file Climb\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.autonomous\&.commandgroups\&.Climb\&.end ()\fC [protected]\fP"

.PP
Definition at line 63 of file Climb\&.java\&.
.SS "void frc\&.robot\&.autonomous\&.commandgroups\&.Climb\&.interrupted ()\fC [protected]\fP"

.PP
Definition at line 55 of file Climb\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
