.TH "frc.robot.Constants.DriveTrain" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.Constants.DriveTrain
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBleftFrontMotor\fP = 1"
.br
.ti -1c
.RI "static final int \fBleftRearMotor\fP = 2"
.br
.ti -1c
.RI "static final int \fBrightFrontMotor\fP = 3"
.br
.ti -1c
.RI "static final int \fBrightRearMotor\fP = 4"
.br
.ti -1c
.RI "static final int \fBpeakCurrent\fP = 35"
.br
.ti -1c
.RI "static final int \fBholdCurrent\fP = 33"
.br
.ti -1c
.RI "static final int \fBcurrentTimeout\fP = 30"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Constants\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final int frc\&.robot\&.Constants\&.DriveTrain\&.currentTimeout = 30\fC [static]\fP"

.PP
Definition at line 19 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DriveTrain\&.holdCurrent = 33\fC [static]\fP"

.PP
Definition at line 18 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DriveTrain\&.leftFrontMotor = 1\fC [static]\fP"

.PP
Definition at line 12 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DriveTrain\&.leftRearMotor = 2\fC [static]\fP"

.PP
Definition at line 13 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DriveTrain\&.peakCurrent = 35\fC [static]\fP"

.PP
Definition at line 17 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DriveTrain\&.rightFrontMotor = 3\fC [static]\fP"

.PP
Definition at line 14 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DriveTrain\&.rightRearMotor = 4\fC [static]\fP"

.PP
Definition at line 15 of file Constants\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
