.TH "frc.robot.commands.CompressorControl" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.commands.CompressorControl \- This command reads driver input to enable and disable the robot's compressor\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Command\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBexecute\fP ()"
.br
.ti -1c
.RI "boolean \fBisFinished\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This command reads driver input to enable and disable the robot's compressor\&. 
.PP
Definition at line 9 of file CompressorControl\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.commands\&.CompressorControl\&.execute ()\fC [protected]\fP"

.PP
Definition at line 15 of file CompressorControl\&.java\&.
.SS "boolean frc\&.robot\&.commands\&.CompressorControl\&.isFinished ()\fC [protected]\fP"

.PP
Definition at line 38 of file CompressorControl\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
