.TH "frc.robot.autonomous.commandgroups" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.commandgroups
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClimb\fP"
.br
.RI "This should be used for going lvl 1 to 3, or 2 to 3\&. "
.ti -1c
.RI "class \fBFailedAutonomous\fP"
.br
.RI "This will only run if the \fBChooser\fP failed to find anything else to do\&. "
.ti -1c
.RI "class \fBHabLeftHatchFront\fP"
.br
.ti -1c
.RI "class \fBHabLeftHatchSide\fP"
.br
.ti -1c
.RI "class \fBHabRightHatchFront\fP"
.br
.ti -1c
.RI "class \fBHabRightHatchSide\fP"
.br
.ti -1c
.RI "class \fBOuttake\fP"
.br
.RI "Handles everything required to shoot a hatch and drop a cargo\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
