.TH "frc.robot.autonomous.actions.HoldArmsUntilLock" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.actions.HoldArmsUntilLock \- Hold the arms at a speed until the climber is 'locked'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Command\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHoldArmsUntilLock\fP (double speed)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBexecute\fP ()"
.br
.ti -1c
.RI "boolean \fBisFinished\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Hold the arms at a speed until the climber is 'locked'\&. 

This effectively holds the arms forever during a climb\&. 
.PP
Definition at line 14 of file HoldArmsUntilLock\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.autonomous\&.actions\&.HoldArmsUntilLock\&.HoldArmsUntilLock (double speed)"

.PP
Definition at line 19 of file HoldArmsUntilLock\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.autonomous\&.actions\&.HoldArmsUntilLock\&.execute ()\fC [protected]\fP"

.PP
Definition at line 24 of file HoldArmsUntilLock\&.java\&.
.SS "boolean frc\&.robot\&.autonomous\&.actions\&.HoldArmsUntilLock\&.isFinished ()\fC [protected]\fP"

.PP
Definition at line 31 of file HoldArmsUntilLock\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
