.TH "frc.robot" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBautonomous\fP"
.br
.ti -1c
.RI "package \fBcommands\fP"
.br
.ti -1c
.RI "package \fBsubsystems\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConstants\fP"
.br
.RI "This is a mapping from the ports sensors and actuators are wired into to a variable name\&. "
.ti -1c
.RI "class \fBLocks\fP"
.br
.ti -1c
.RI "class \fBMain\fP"
.br
.RI "Do NOT add any static variables to this class, or any initialization at all\&. "
.ti -1c
.RI "class \fBOI\fP"
.br
.RI "This class is the glue that binds the controls on the physical operator interface to the commands and command groups that allow control of the robot\&. "
.ti -1c
.RI "class \fBRobot\fP"
.br
.RI "The VM is configured to automatically run this class, and to call the functions corresponding to each mode, as described in the TimedRobot documentation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
