.TH "frc.lib5k.control.SlewLimiter" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.lib5k.control.SlewLimiter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSlewLimiter\fP (double limit)"
.br
.ti -1c
.RI "double \fBfeed\fP (double value)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file SlewLimiter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.lib5k\&.control\&.SlewLimiter\&.SlewLimiter (double limit)"

.PP
Definition at line 7 of file SlewLimiter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double frc\&.lib5k\&.control\&.SlewLimiter\&.feed (double value)"

.PP
Definition at line 11 of file SlewLimiter\&.java\&.
.SS "void frc\&.lib5k\&.control\&.SlewLimiter\&.reset ()"

.PP
Definition at line 22 of file SlewLimiter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
