.TH "frc.robot.autonomous.actions.SetBrakes" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.autonomous.actions.SetBrakes \- Sets the DriveTrain's brakes in autonomous\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Command\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetBrakes\fP (boolean on)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "boolean \fBisFinished\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sets the DriveTrain's brakes in autonomous\&. 
.PP
Definition at line 9 of file SetBrakes\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.autonomous\&.actions\&.SetBrakes\&.SetBrakes (boolean on)"

.PP
Definition at line 13 of file SetBrakes\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void frc\&.robot\&.autonomous\&.actions\&.SetBrakes\&.initialize ()\fC [protected]\fP"

.PP
Definition at line 18 of file SetBrakes\&.java\&.
.SS "boolean frc\&.robot\&.autonomous\&.actions\&.SetBrakes\&.isFinished ()\fC [protected]\fP"

.PP
Definition at line 23 of file SetBrakes\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
