.TH "frc.robot.commands" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.commands
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClimbControl\fP"
.br
.RI "This command starts other climb commands depending on 2fa inputs\&. "
.ti -1c
.RI "class \fBCompressorControl\fP"
.br
.RI "This command reads driver input to enable and disable the robot's compressor\&. "
.ti -1c
.RI "class \fBDriveControl\fP"
.br
.RI "Control the \fBRobot\fP's drivebase with \fBOI\fP feedback\&. "
.ti -1c
.RI "class \fBIntakeControl\fP"
.br
.RI "Command for controlling intake commands from drivers\&. "
.ti -1c
.RI "class \fBManualArmController\fP"
.br
.RI "This command is run by \fBClimbControl\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
