.TH "frc.robot.Constants.DIO" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.Constants.DIO
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBslider_left_limit\fP = 3"
.br
.ti -1c
.RI "static final int \fBslider_centre_limit\fP = 8"
.br
.ti -1c
.RI "static final int \fBslider_right_limit\fP = 0"
.br
.ti -1c
.RI "static final int \fBarm_sensor\fP = 4"
.br
.ti -1c
.RI "static final int \fBoptics_sensor\fP = 7"
.br
.ti -1c
.RI "static final int \fBleg_top\fP = 1"
.br
.ti -1c
.RI "static final int \fBleg_mid\fP = 5"
.br
.ti -1c
.RI "static final int \fBleg_low\fP = 6"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file Constants\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final int frc\&.robot\&.Constants\&.DIO\&.arm_sensor = 4\fC [static]\fP"

.PP
Definition at line 96 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DIO\&.leg_low = 6\fC [static]\fP"

.PP
Definition at line 102 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DIO\&.leg_mid = 5\fC [static]\fP"

.PP
Definition at line 101 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DIO\&.leg_top = 1\fC [static]\fP"

.PP
Definition at line 100 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DIO\&.optics_sensor = 7\fC [static]\fP"

.PP
Definition at line 98 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DIO\&.slider_centre_limit = 8\fC [static]\fP"

.PP
Definition at line 93 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DIO\&.slider_left_limit = 3\fC [static]\fP"

.PP
Definition at line 92 of file Constants\&.java\&.
.SS "final int frc\&.robot\&.Constants\&.DIO\&.slider_right_limit = 0\fC [static]\fP"

.PP
Definition at line 94 of file Constants\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
