.TH "frc.lib5k.loops.loopables" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.lib5k.loops.loopables
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLoopableSubsystem\fP"
.br
.RI "A replacement for WPIlib's Subsystem\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
