.TH "src/main/java/frc/lib5k/components/GearBox.java" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/java/frc/lib5k/components/GearBox.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfrc\&.lib5k\&.components\&.GearBox\fP"
.br
.RI "A \fBGearBox\fP is a wrapper for any pair of WPI_TalonSRX motor controllers where the first controller has an encoder attached\&. "
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBfrc\&.lib5k\&.components\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
