.TH "src/main/java/frc/robot/OI.java" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/java/frc/robot/OI.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfrc\&.robot\&.OI\fP"
.br
.RI "This class is the glue that binds the controls on the physical operator interface to the commands and command groups that allow control of the robot\&. "
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBfrc\&.robot\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
