.TH "src/main/java/frc/lib5k/spatial/Rotation2D.java" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/java/frc/lib5k/spatial/Rotation2D.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfrc\&.lib5k\&.spatial\&.Rotation2D\fP"
.br
.RI "A rotation in a 2d coordinate frame represented a point on the unit circle (cosine and sine)\&. "
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBfrc\&.lib5k\&.spatial\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
