.TH "vision.WebcamVideoStream" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vision.WebcamVideoStream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, camera, \fBcameraServer\fP, frameWidth, frameHeight, \fBname\fP='WebcamVideoStream')"
.br
.ti -1c
.RI "def \fBstart\fP (self)"
.br
.ti -1c
.RI "def \fBupdate\fP (self)"
.br
.ti -1c
.RI "def \fBread\fP (self)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.ti -1c
.RI "def \fBgetError\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwebcam\fP"
.br
.ti -1c
.RI "\fBautoExpose\fP"
.br
.ti -1c
.RI "\fBprevValue\fP"
.br
.ti -1c
.RI "\fBimg\fP"
.br
.ti -1c
.RI "\fBstream\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBstopped\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file vision\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def vision\&.WebcamVideoStream\&.__init__ ( self,  camera,  cameraServer,  frameWidth,  frameHeight,  name = \fC'WebcamVideoStream'\fP)"

.PP
Definition at line 84 of file vision\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def vision\&.WebcamVideoStream\&.getError ( self)"

.PP
Definition at line 137 of file vision\&.py\&.
.SS "def vision\&.WebcamVideoStream\&.read ( self)"

.PP
Definition at line 130 of file vision\&.py\&.
.SS "def vision\&.WebcamVideoStream\&.start ( self)"

.PP
Definition at line 107 of file vision\&.py\&.
.SS "def vision\&.WebcamVideoStream\&.stop ( self)"

.PP
Definition at line 134 of file vision\&.py\&.
.SS "def vision\&.WebcamVideoStream\&.update ( self)"

.PP
Definition at line 114 of file vision\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "vision\&.WebcamVideoStream\&.autoExpose"

.PP
Definition at line 92 of file vision\&.py\&.
.SS "vision\&.WebcamVideoStream\&.img"

.PP
Definition at line 95 of file vision\&.py\&.
.SS "vision\&.WebcamVideoStream\&.name"

.PP
Definition at line 101 of file vision\&.py\&.
.SS "vision\&.WebcamVideoStream\&.prevValue"

.PP
Definition at line 93 of file vision\&.py\&.
.SS "vision\&.WebcamVideoStream\&.stopped"

.PP
Definition at line 105 of file vision\&.py\&.
.SS "vision\&.WebcamVideoStream\&.stream"

.PP
Definition at line 97 of file vision\&.py\&.
.SS "vision\&.WebcamVideoStream\&.webcam"

.PP
Definition at line 89 of file vision\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
