.TH "vision.FPS" 3 "Sat Aug 31 2019" "Version 2019" "DeepSpace-SWI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vision.FPS
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBstart\fP (self)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.ti -1c
.RI "def \fBupdate\fP (self)"
.br
.ti -1c
.RI "def \fBelapsed\fP (self)"
.br
.ti -1c
.RI "def \fBfps\fP (self)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_start\fP"
.br
.ti -1c
.RI "\fB_end\fP"
.br
.ti -1c
.RI "\fB_numFrames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file vision\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def vision\&.FPS\&.__init__ ( self)"

.PP
Definition at line 27 of file vision\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def vision\&.FPS\&.elapsed ( self)"

.PP
Definition at line 48 of file vision\&.py\&.
.SS "def vision\&.FPS\&.fps ( self)"

.PP
Definition at line 53 of file vision\&.py\&.
.SS "def vision\&.FPS\&.start ( self)"

.PP
Definition at line 34 of file vision\&.py\&.
.SS "def vision\&.FPS\&.stop ( self)"

.PP
Definition at line 39 of file vision\&.py\&.
.SS "def vision\&.FPS\&.update ( self)"

.PP
Definition at line 43 of file vision\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "vision\&.FPS\&._end\fC [private]\fP"

.PP
Definition at line 31 of file vision\&.py\&.
.SS "vision\&.FPS\&._numFrames\fC [private]\fP"

.PP
Definition at line 32 of file vision\&.py\&.
.SS "vision\&.FPS\&._start\fC [private]\fP"

.PP
Definition at line 30 of file vision\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace-SWI from the source code\&.
