name: FRC Build & Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Run FRC tests
      uses: ewpratten/FRC-actions@v0.7
      with:
        build_mode: 'all'
